---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Eixo-Docker
no_index:
  directory:
    - t
    - inc
requires:
  Eixo::Base: 1
  Eixo::Rest: 1
  JSON: 2.5
  Net::HTTP: 6.06
version: 1.063
